# Ch02 PyTorch基础教程

## 2.1 张量数据类型

In [16]:
import torch
import numpy as np

In [8]:
a = torch.randn(2,3)
print(a.type())
print(type(a))
isinstance(a,torch.FloatTensor)

torch.FloatTensor
<class 'torch.Tensor'>


True

### Note1: 类型推断
- tensor_name.type()
- isinstance(torsor_name,type_name)

In [12]:
# 标量 ,dim=0
a = torch.tensor(1.)
print(a,a.shape,len(a.shape),a.dim())

tensor(1.) torch.Size([]) 0 0


### Note2: dim=0 标量
- a.shape 成员
- a.size() 成员函数
- a.dim() 维度

In [18]:
# 向量,dim=1
a = torch.tensor([1.1,2.2])
print(a,a.shape,a.type())

b = torch.FloatTensor(2)
print(b,b.shape,b.type())

data = np.ones(2)
c = torch.from_numpy(data)
print(c,c.shape,c.type())

tensor([1.1000, 2.2000]) torch.Size([2]) torch.FloatTensor
tensor([8.4078e-45, 0.0000e+00]) torch.Size([2]) torch.FloatTensor
tensor([1., 1.], dtype=torch.float64) torch.Size([2]) torch.DoubleTensor


### Note3: dim=1 向量
- .tensor接受的是数据的内容
- .FloatTensor接受的是数据的shape,随机初始化
- .from_numpy()  numpy -> torch.tensor
- dim=0 -> 0.1
- dim=1 -> [0.1]


In [26]:
a = torch.randn(2,3) # normal distribution 正态分布
# a = torch.FloatTensor(2,3)
print(a)
print(a.shape,' ',a.size(0),' ',a.size(1))
print('用shape索引: ',a.shape[0],' ',a.shape[1])

tensor([[-0.6025, -0.0328, -1.7973],
        [ 0.5828,  0.6371, -0.0266]])
torch.Size([2, 3])   2   3
用shape索引:  2   3


In [33]:
a = torch.rand(1,2,3)   #  均匀分布[0,1] uniform distribution
display(a)
print(a.shape,' ',a.size())
list(a.shape)
print('a的内存大小为:1x2x3 = ',a.numel())
print(len(a.shape),a.dim())

tensor([[[0.9681, 0.9093, 0.3873],
         [0.2986, 0.7554, 0.5381]]])

torch.Size([1, 2, 3])   torch.Size([1, 2, 3])
a的内存大小为:1x2x3 =  6
3 3


### Note4: dim=3的张量
- rand 均匀分布[0,1]
- randn 正态分布[0,1]
- 为了和python交互,使用list将shape转换为list类型
- 用.numel()方法得到tensor的大小
- 用len(a.shape)和a.dim()都可得到tensor的维度
- 三维张量在RNN经常使用,四维张量在CNN中经常使用,用来表示图片

## 2.2 创建Tensor

In [35]:
a_np = np.array([2,3.3])
a_pt = torch.from_numpy(a_np)
a_pt

tensor([2.0000, 3.3000], dtype=torch.float64)

In [36]:
torch.tensor([2.,3.2]) # 小写给具体数据

tensor([2.0000, 3.2000])

In [38]:
torch.FloatTensor(2,3) # 大写给shape
# torch.FloatTensor([2.,3.2]) 少使用,易混淆

tensor([[9.8863e+36, 4.5790e-41, 9.8866e+36],
        [4.5790e-41, 2.7604e+20, 1.7744e+28]])

In [46]:
# set default type
print(torch.tensor([1.2,3]).type())
torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.2,3]).type())

torch.FloatTensor
torch.DoubleTensor


### Note5: tensor和FloatTensor
- 小写给具体数据,大写给shape
- 这种方法生成的张量不能直接使用,里面会存在无穷大和无穷小,后面必须用别的数据写入
- .set_default_tensor_type()方法可以设置tensor的默认类型

In [51]:
# rand
a = torch.rand(3,3)
print(a)
b = torch.rand_like(a)
print(a)

a = torch.randint(1,10,[3,3])
print(a)

tensor([[0.2782, 0.6091, 0.6666],
        [0.3973, 0.5082, 0.8371],
        [0.4828, 0.8271, 0.6257]])
tensor([[0.2782, 0.6091, 0.6666],
        [0.3973, 0.5082, 0.8371],
        [0.4828, 0.8271, 0.6257]])
tensor([[5, 4, 8],
        [3, 3, 2],
        [6, 8, 2]])


### Note6: rand/rand_like , randint
- rand会均匀随机产生[0,1)之间的数据
- *_like方法接收的参数是tensor
- .randint(1,10,[3,3])产生[1,10)之间的均匀分布随机数,shape为[3,3]

In [60]:
# randn正太分布   N(0,1)
a = torch.rand(3,3)
print(a)

# N(u,std)
print(torch.normal(mean=torch.full([10],0),std=torch.arange(1,0,-0.1)))

print('\n\n')

# full
print('想把tensor全部赋值为一个元素用full: \n',torch.full([2,3],7))
print('生成一个标量:\n',torch.full([],7))
print('生成一个vec:\n',torch.full([2],7))

print('\n\n')


tensor([[0.7122, 0.9045, 0.0039],
        [0.8279, 0.5099, 0.2207],
        [0.0466, 0.6949, 0.9866]])
tensor([ 1.8412,  0.0322,  0.7769,  0.7791,  0.2126,  0.1222, -0.2154,  0.2899,
         0.3680,  0.1192])



想把tensor全部赋值为一个元素用full: 
 tensor([[7., 7., 7.],
        [7., 7., 7.]])
生成一个标量:
 tensor(7.)
生成一个vec:
 tensor([7., 7.])





### Note7: randn , full
- randn正态分布
- full将tensor全部赋值为一个元素

In [64]:
# arrange/range
print('arange生成[0,10)内的等差为2的数列: \n',torch.arange(0,10,2))
print('\n')

arange生成[0,10)内的等差为2的数列: 
 tensor([0, 2, 4, 6, 8])




In [70]:
# linespace/logspace
print('linespace在[0,10]中生成4个间隔相同的数字: \n',torch.linspace(0,10,steps=4))
print('logspace在[-1,0]中切割10份,设每个数为xi,生成10^xi: \n',torch.logspace(0,-1,steps=10,base=10))

linespace在[0,10]中生成4个间隔相同的数字: 
 tensor([ 0.0000,  3.3333,  6.6667, 10.0000])
logspace在[-1,0]中切割10份,设每个数为xi,生成10^xi: 
 tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])


### Note8: arange/range  linespace/logspace
- pytorch不建议使用range
- arange的第三个参数是等差
- linespace的第三个参数是等分的数量
- logspace的base参数可以设置为2,10,e等底数

In [73]:
print(torch.ones(3,3))
print(torch.zeros(3,3))
print(torch.eye(3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### Note9: ones/zeros/eye , ones_like/zeros_like/eye_like

In [87]:
print('生成[0,10)的随机索引, 可以用来shuffle : \n',torch.randperm(10))

生成[0,10)的随机索引, 可以用来shuffle : 
 tensor([4, 1, 9, 3, 2, 6, 8, 7, 0, 5])


### Note10: randperm 
- 生成随机索引

## 2.3 索引与切片

In [124]:
a = torch.rand(4,3,28,28) # [batch_size , channel , Height, width]
print('a的shape: ',a.shape)
print('a[0]的shape:  ',a[0].shape)
print('a[0,0]的shape:  ',a[0,0].shape)
print('a[0,0,1,1]的shape:  ',a[0,0,1,1].shape,'\n') # 标量

print('选取连续范围的张量:')
print('a的shape: ',a.shape)
print('a[:2]的shape: ',a[:2].shape)
print('a[:2,:1,:,:]: ',a[:2,:1,:,:].shape) # 单个:表示取全部
print('a[:2,1:,:,:]: ',a[:2,1:].shape)
print('a[:2,-1:,:,:]: ',a[:2,-1:,:,:].shape,'\n') # 负数代表反向取

print('选取带step的张量')
print('a的shape: ',a.shape)
print('a[:,:,0:28:2,0:28:2]的shape: ',a[:,:,0:28:2,:28:2].shape)
print('a[:,:,::2,::2].shape: ',a[:,:,::2,::2].shape,'\n')

print('根据具体的索引采样')
print('a的shape: ',a.shape)
print('a.index_select(0,torch.tensor([0,2])).shape 第0维度上索引为[0,2]的两张图片 :',
      a.index_select(0,torch.tensor([0,2])).shape)
print('a.index_select(2,torch.arange(8)).shape  第2个维度上索引为0-8行的内容: ',
     a.index_select(2,torch.arange(8)).shape,'\n')

print('用...来索引, ...代表任意多的维度')
print('a的shape: ',a.shape)
print('a[...].shape: ',a[...].shape)
print('a[:,1,...].shape ',a[:,1,...].shape,'\n')


print('使用掩码索引')
x = torch.randn(3,4)
print('x.shape: ',x.shape)
mask = x.ge(0.5) # GreaterEqual,大于等于0.5 ,mask中大于等于5置为1,其余为0
print('torch.masked_select(x,mask): ',torch.masked_select(x,mask))
print('Shape为: ',torch.masked_select(x,mask).shape)

print('\n用take索引,即先flatten后再索引,')
a = torch.tensor([[4,3,5],[6,7,8]])
print(a,'\n',a.shape)
print('torch.take(a,torch.tensor([0,2,5])): ',torch.take(a,torch.tensor([0,2,5])))
print('Shape: ',torch.take(a,torch.tensor([0,2,5])).shape)

a的shape:  torch.Size([4, 3, 28, 28])
a[0]的shape:   torch.Size([3, 28, 28])
a[0,0]的shape:   torch.Size([28, 28])
a[0,0,1,1]的shape:   torch.Size([]) 

选取连续范围的张量:
a的shape:  torch.Size([4, 3, 28, 28])
a[:2]的shape:  torch.Size([2, 3, 28, 28])
a[:2,:1,:,:]:  torch.Size([2, 1, 28, 28])
a[:2,1:,:,:]:  torch.Size([2, 2, 28, 28])
a[:2,-1:,:,:]:  torch.Size([2, 1, 28, 28]) 

选取带step的张量
a的shape:  torch.Size([4, 3, 28, 28])
a[:,:,0:28:2,0:28:2]的shape:  torch.Size([4, 3, 14, 14])
a[:,:,::2,::2].shape:  torch.Size([4, 3, 14, 14]) 

根据具体的索引采样
a的shape:  torch.Size([4, 3, 28, 28])
a.index_select(0,torch.tensor([0,2])).shape 第0维度上索引为[0,2]的两张图片 : torch.Size([2, 3, 28, 28])
a.index_select(2,torch.arange(8)).shape  第2个维度上索引为0-8行的内容:  torch.Size([4, 3, 8, 28]) 

用...来索引, ...代表任意多的维度
a的shape:  torch.Size([4, 3, 28, 28])
a[...].shape:  torch.Size([4, 3, 28, 28])
a[:,1,...].shape  torch.Size([4, 28, 28]) 

使用掩码索引
x.shape:  torch.Size([3, 4])
torch.masked_select(x,mask):  tensor([0.9662, 1.1723, 0.7542])
Shape为:

### Note11: 索引与切片的多种方式
- 选取连续范围的张量
- 选取带step的张量
- 根据具体的索引采样
- 用...来索引, ...代表任意多的维度
- 使用掩码索引,结果是个一维向量
- 使用take索引,先flatten打平然后索引

## 2.4 维度变换
- View/reshape
- Squeeze/unsqueeze
- Transpose/t/permute
- Expand/repeat

In [146]:
# view reshape等价
a = torch.rand(4,1,28,28)
print('view/reshape:')
print('a.shape: ',a.shape)
print('a.view(4,28*28): ',a.view(4,28*28).shape,'\n')

print('Squeeze v.s. unsqueeze:')
print('a.shape: ',a.shape)
print('参数是正数,在这个索引之前插入,参数是负数,在这个索引之后插入')
print('a.unsqueeze(0): ',a.unsqueeze(0).shape)
print('a.unsqueeze(-1): ',a.unsqueeze(-1).shape)
a = torch.tensor([1.2,2.3])
print('a: ',a)
print('a.unsqueeze(-1): ',a.unsqueeze(-1),' ',a.unsqueeze(-1).shape)
print('a.unsqueeze(0): ',a.unsqueeze(0),' ',a.unsqueeze(0).shape)

print('\nunsqueeze实例:')
b = torch.rand(32)
f = torch.rand(4,32,14,14)
print('unsqueeze b 之前: ',b.shape)
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)

print('b.unsqueeze(1).unsqueeze(2).unsqueeze(0)后: ',b.shape)

print('\nsqueeze操作:')
print('b.shape: ',b.shape)
print('b.squeeze()后: ',b.squeeze().shape)
print('b.squeeze(0)后: ',b.squeeze(0).shape)
print('b.squeeze(-4)后: ',b.squeeze(-4).shape)

print('\nexpand操作:')
a = torch.rand(4,32,14,14)
print('b.shape: ',b.shape)
print('b.expand(4,32,14,14)后: ',b.expand(4,32,14,14).shape)
print('b.expand(-1,32,-1,-1)后: ',b.expand(-1,32,-1,-1).shape)

print('\nrepeat操作:')
print('b.shape: ',b.shape)
print('b.repeat(4,32,1,1)后: ',b.repeat(4,32,1,1).shape)
print('repeat中的参数表示重复的次数,所以是32*32=1024')

view/reshape:
a.shape:  torch.Size([4, 1, 28, 28])
a.view(4,28*28):  torch.Size([4, 784]) 

Squeeze v.s. unsqueeze:
a.shape:  torch.Size([4, 1, 28, 28])
参数是正数,在这个索引之前插入,参数是负数,在这个索引之后插入
a.unsqueeze(0):  torch.Size([1, 4, 1, 28, 28])
a.unsqueeze(-1):  torch.Size([4, 1, 28, 28, 1])
a:  tensor([1.2000, 2.3000])
a.unsqueeze(-1):  tensor([[1.2000],
        [2.3000]])   torch.Size([2, 1])
a.unsqueeze(0):  tensor([[1.2000, 2.3000]])   torch.Size([1, 2])

unsqueeze实例:
unsqueeze b 之前:  torch.Size([32])
b.unsqueeze(1).unsqueeze(2).unsqueeze(0)后:  torch.Size([1, 32, 1, 1])

squeeze操作:
b.shape:  torch.Size([1, 32, 1, 1])
b.squeeze()后:  torch.Size([32])
b.squeeze(0)后:  torch.Size([32, 1, 1])
b.squeeze(-4)后:  torch.Size([32, 1, 1])

expand操作:
b.shape:  torch.Size([1, 32, 1, 1])
b.expand(4,32,14,14)后:  torch.Size([4, 32, 14, 14])
b.expand(-1,32,-1,-1)后:  torch.Size([1, 32, 1, 1])

repeat操作:
b.shape:  torch.Size([1, 32, 1, 1])
b.repeat(4,32,1,1)后:  torch.Size([4, 1024, 1, 1])
repeat中的参数表示重复的次数,所以是32*32

### Note12: 维度变换
- view/reshape
- squeeze v.s. unsqueeze
- 维度扩张
 - expand:broadcasting(推荐使用)
 - repeat:memory copied (参数是重复的次数)

In [159]:
# 转秩操作
a = torch.rand(3,4)
print('a:\n',a)
print('a.T:\n',a.T)
print('.T操作只适用于2D tensor\n')

a = torch.rand(4,3,32,32)
print('a.shape: ',a.shape)
a1 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32)
print('a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32):\n',a1.shape,'\n')
a2 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,32,32,3).transpose(1,3)
print('a.transpose(1,3).contiguous(),view(4,3*32*32).view(4,32,32,3).transpose(1,3):\n',a2.shape,'\n')

print('a1.shape: ',a1.shape)
print('a2.shape: ',a2.shape)
print('a = a1 ? ',torch.all(torch.eq(a,a1)))
print('a = a2 ? ',torch.all(torch.eq(a,a2)))

a:
 tensor([[0.8286, 0.4806, 0.9881, 0.5412],
        [0.5168, 0.8315, 0.1288, 0.5200],
        [0.5800, 0.0461, 0.9936, 0.5407]])
a.T:
 tensor([[0.8286, 0.5168, 0.5800],
        [0.4806, 0.8315, 0.0461],
        [0.9881, 0.1288, 0.9936],
        [0.5412, 0.5200, 0.5407]])
.T操作只适用于2D tensor

a.shape:  torch.Size([4, 3, 32, 32])
a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32):
 torch.Size([4, 3, 32, 32]) 

a.transpose(1,3).contiguous(),view(4,3*32*32).view(4,32,32,3).transpose(1,3):
 torch.Size([4, 3, 32, 32]) 

a1.shape:  torch.Size([4, 3, 32, 32])
a2.shape:  torch.Size([4, 3, 32, 32])
a = a1 ?  tensor(False)
a = a2 ?  tensor(True)


### Note12: Transpose
a.shape # [4,3,32,32] -> [b c h w] 

如果要交换第一维和第三维 , a.transpose(1,3)  : [b c h w] -> [b w h c] , 

如果把后三个维度连在一起理解, 即 a.transpose(1,3).view(4,3*32*32) , 

再展开a.transpose(1,3).view(4,3*32*32).view(4,3,32,32) , -> [b c w h]

由于view操作会把维度信息丢掉,使用transpose后,[b c h w] -> [b w h c], 后面进行view(4,3,32,32)操作时候,是按[b c h w]的顺序展开的,这是错误的,因为维度顺序已经变成了[b w h c ],正确的写法是view(4,32,32,3), **数据的维度顺序必须和存储顺序一致** 

transpose涉及维度的交换,原来的数据存储方式会发生改变,数据会变得不连续,需要使用.contiguous()方法把数据重新变成连续的,然后再view

- 用.eq比较a和a1是否相等,再用torch.all()方法表示所有元素都是一致的时候才返回True


In [166]:
# permute
a = torch.rand(4,3,28,32) # 变换为 -> [4,28,32,3]
print('用transpose方法:')
print('a.shape: ',a.shape)
print('a.transpose(1,3).transpose(1,2): ',a.transpose(1,3).transpose(1,2).shape)
print('等价于:')
print('a.permute(0,2,3,1): ',a.permute(0,2,3,1).shape)

用transpose方法:
a.shape:  torch.Size([4, 3, 28, 32])
a.transpose(1,3).transpose(1,2):  torch.Size([4, 28, 32, 3])
等价于:
a.permute(0,2,3,1):  torch.Size([4, 28, 32, 3])


### Note13: permute
- 可以完成任意次数的交换,按照交换前后的索引号填写参数